language: rust
rust:
  - 1.3.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo doc
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo test --verbose;
      cargo bench --verbose --features nightly;
    fi
